### ISSUE TITLE
"build-cycles " folder missed

### ISSUE THREAD

**Issue by atsap** [kenaniah/swords-and-potions-2-bot#1]
Hi, I download the zip and try to run on python 2.7. It seems you not provide the "build-cycles" related files.

**Comment by kenaniah** [comment]
I'll need to add this to the readme. The build-cycles folder should
contain  screenshots of the items you want for that employee to build. The
bot will cycle through each screenshot in order, and will attempt to build
a random item if the item in the screenshot could not be built.
Naturally, the item you want to build should be on the first page of your
employee's build list.

As the game progresses, you may also have to add screenshots of other
customers as well.

**Comment by atsap** [comment]
ok. It works now for me, thanks.
