### ISSUE TITLE
Syntax error while running

### ISSUE THREAD

**Issue by thejk7** [kenaniah/swords-and-potions-2-bot#2]
Hey!

I just downloaded your script and tried using it for S&P 2, but I got a syntax error as soon as I ran it in python. What might be the problem?

**Comment by kenaniah** [comment]
Please paste the stack trace and what version of python you are using. Your question is unanswerable without that information :-)

**Comment by thejk7** [comment]
I'm using Python 3.4.1

By stack trace you mean the report where the reason for error should be noted down? Sorry, I'm a newbie at this :D

The error comes before python has even printed first line.

**Comment by kenaniah** [comment]
Yup. Just copy/paste the entire output. For the record, there's no point in
stating you had an error unless you describe it with relevant details :-)

**Comment by thejk7** [comment]
This is all I see.
![error](https://cloud.githubusercontent.com/assets/8036996/3455203/4d7cb764-01dd-11e4-9680-9f9c708efa10.png)

**Comment by dran121** [comment]
I'm having the same issue and id assume that it is related to these lines in the code 

# Environment setup

os.chdir(os.path.dirname(**file**))
sys.path.append(r"C:\automa\library.zip")
from automa.api import *

**Comment by raven128** [comment]
that error occure because the developer uses third party API Automa that he doesn't include in this package. and Automa API is only 30 days trial, and then one should pay for a license

**Comment by kenaniah** [comment]
I've added a readme that talks about both the Automa API and the Python version. Please let me know if you run into anything else.
