### ISSUE TITLE
Can you help me? error. i guess..

### ISSUE THREAD

**Issue by kramp2** [kenaniah/swords-and-potions-2-bot#4]
I got this error:

Traceback (most recent call last):
  File "C:\Users\Karan\Downloads\Automa\swords-and-potions-2-bot-master\snp2-bot.py", line 16, in <module>
    os.chdir(os.path.dirname(**file**))
NameError: name '**file**' is not defined

I don't get it..

**Comment by kenaniah** [comment]
I'm going to guess that you're using an old version of python. You need at least python 2.7 to run the not.

**Comment by kenaniah** [comment]
*bot

**Comment by kramp2** [comment]
Hi,
The error is gone now. But the thing now is. It just keeps on scanning for images, it doesn't assign the workers. I replaced the screenshots of the employees. 
Also it doesn't interact with the customers. 
How can i solve this and get it working? 

Thanks a lot!!!

**Comment by kenaniah** [comment]
I'm assuming you're implying that the bot actually does find other images, such as the next day sign. If that's the case, the screenshots you must have taken may be too unique. Automa performs a grey-scale image similarity comparison -- it does not recognize objects. Therefore, your images **must not** have any sort of background noise in them. 

If the bot runs but does not match any of the images at all, there may be another problem at hand.
