### ISSUE TITLE
Don't buy, sell or craft

### ISSUE THREAD

**Issue by petitchoe** [kenaniah/swords-and-potions-2-bot#6]
Was problem with version of python, but now is ok. Bot don't working for me. Can you write me mail for consultation? My email is ljashenkov@gmail.com

**Comment by kenaniah** [comment]
Please see the FAQ in the readme as the most common reasons are covered there. If you are still having problems after following the advice in the readme, please create a new issue with details as to what works and what does not. General statements like "it doesn't work" does not give anyone the information they need to actually help you.
